name: reproduction

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ios-version: ["18.4", "18.5", "18.6"]
        maestro-version: [2.0.3]
        xcode-version: [16.3, 16.4]
    name: "test(maestro: ${{ matrix.maestro-version }}, ios: ${{ matrix.ios-version }}, xcode: ${{ matrix.xcode-version }})"
    runs-on: macos-15
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4

      - name: 🏗️ Set up Node.js
        uses: ./.github/actions/set-up-node-js

      - name: 🏗️ Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version  }}

      - name: 🏗️ Set up Maestro
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
        env:
          MAESTRO_VERSION: ${{ matrix.maestro-version }}

      - name: 🚚 Install dependencies
        run: yarn install

      - name: 📱 Launch iOS simulator
        id: launch-ios-simulator
        uses: ./.github/actions/launch-ios-simulator
        with:
          model: "iPhone 16"
          os: "iOS"
          os-version: ${{ matrix.ios-version }}

      - name: 📲 Install app
        run: xcrun simctl install booted $GITHUB_WORKSPACE/build/maestroiosdeeplinkmcve.app

      - name: 🧪 Run tests
        run: yarn run test:end-to-end
        env:
          MAESTRO_DRIVER_STARTUP_TIMEOUT: 300000

      - name: 💾 Save test artifacts
        if: cancelled() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-ios-${{ matrix.ios-version }}-maestro-${{ matrix.maestro-version }}-xcode-${{ matrix.xcode-version }}
          path: ~/.maestro/tests
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 30
